# Generated by Django 5.2.12 on 2026-05-23 13:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название достижения')),
                ('icon_class', models.CharField(default='fas fa-medal', max_length=50, verbose_name='Иконка (Font Awesome)')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Очки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сообщества')),
                ('icon_class', models.CharField(default='fas fa-users', max_length=50, verbose_name='Иконка (Font Awesome)')),
                ('description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('member_count', models.PositiveIntegerField(default=0, verbose_name='Количество участников')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-идентификатор')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень')),
                ('duration_weeks', models.PositiveIntegerField(default=4, verbose_name='Длительность (недель)')),
                ('lessons_count', models.PositiveIntegerField(default=10, verbose_name='Количество уроков')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (₽)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена (₽)')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный')),
                ('icon_class', models.CharField(default='fas fa-language', max_length=50, verbose_name='Иконка (Font Awesome)')),
                ('badge_text', models.CharField(blank=True, help_text='Например: "🔥 АКЦИЯ"', max_length=50, verbose_name='Текст бейджа')),
                ('badge_color', models.CharField(default='warning', max_length=20, verbose_name='Цвет бейджа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликован')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название лиги')),
                ('tatar_name', models.CharField(max_length=50, verbose_name='Название на татарском')),
                ('rank_order', models.PositiveIntegerField(unique=True, verbose_name='Порядок (1 - низшая)')),
                ('min_users', models.PositiveIntegerField(default=10, verbose_name='Минимум пользователей для создания')),
                ('max_users', models.PositiveIntegerField(default=30, verbose_name='Максимум пользователей')),
            ],
            options={
                'ordering': ['rank_order'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('tatar_name', models.CharField(max_length=100, verbose_name='Название на татарском')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('bonus_xp', models.PositiveIntegerField(default=0, verbose_name='Бонус XP за урок')),
                ('bonus_coins', models.PositiveIntegerField(default=0, verbose_name='Бонус монет')),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('tatar_name', models.CharField(max_length=100, verbose_name='Название на татарском')),
                ('item_type', models.CharField(choices=[('streak_protect', 'Тумар защиты (защита ударного темпа)'), ('xp_boost', 'Курай-ускоритель (удвоение XP на 10 минут)'), ('retry_boost', 'Чак-чак энергии (восстановление попыток теста)'), ('golden_skullcap', 'Золотая тюбетейка (доступ к супер-тесту)'), ('clan_bet', 'Спор батыра (удвоение монет за 7 дней)')], max_length=20, verbose_name='Тип')),
                ('price_coins', models.PositiveIntegerField(default=0, verbose_name='Цена (монеты)')),
                ('price_tulips', models.PositiveIntegerField(default=0, verbose_name='Цена (тюльпаны)')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность эффекта (мин)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('icon_class', models.CharField(default='fas fa-box', max_length=50, verbose_name='Иконка')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_number', models.PositiveIntegerField(verbose_name='Номер копии')),
                ('current_week_start', models.DateField(default=django.utils.timezone.now, verbose_name='Начало текущей недели')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='main.league')),
            ],
            options={
                'unique_together': {('league', 'instance_number')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.CharField(blank=True, help_text='Например: Основы, Повседневная речь', max_length=100, verbose_name='Раздел')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('content', models.TextField(blank=True, help_text='HTML формат', verbose_name='Содержание урока')),
                ('duration_minutes', models.PositiveIntegerField(default=10, verbose_name='Длительность (минут)')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='Бесплатный просмотр')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Всего очков (XP)')),
                ('coins', models.PositiveIntegerField(default=0, verbose_name='Монеты')),
                ('tulips', models.PositiveIntegerField(default=0, verbose_name='Тюльпаны (премиум валюта)')),
                ('lessons_completed', models.PositiveIntegerField(default=0, verbose_name='Пройдено уроков')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень')),
                ('streak_days', models.PositiveIntegerField(default=0, verbose_name='Дней подряд')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Дата последней активности')),
                ('weekly_xp', models.PositiveIntegerField(default=0, verbose_name='XP за текущую неделю')),
                ('max_xp_day', models.PositiveIntegerField(default=0, verbose_name='Максимум XP за день')),
                ('best_league_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Лучший результат в лиге (место)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('option1', models.CharField(max_length=200, verbose_name='Вариант 1')),
                ('option2', models.CharField(max_length=200, verbose_name='Вариант 2')),
                ('option3', models.CharField(blank=True, max_length=200, verbose_name='Вариант 3')),
                ('option4', models.CharField(blank=True, max_length=200, verbose_name='Вариант 4')),
                ('correct_option', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Номер правильного ответа (1-4)')),
                ('explanation', models.TextField(blank=True, verbose_name='Пояснение к ответу')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы тестов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Действителен до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Активирован')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_auto_renew', models.BooleanField(default=False, verbose_name='Автопродление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='Номер уровня')),
                ('required_value', models.PositiveIntegerField(verbose_name='Необходимое значение')),
                ('points_reward', models.PositiveIntegerField(default=50, verbose_name='Награда XP')),
                ('coin_reward', models.PositiveIntegerField(default=20, verbose_name='Награда монет')),
                ('tulip_reward', models.PositiveIntegerField(default=0, verbose_name='Награда тюльпанов')),
                ('icon_class', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='main.achievement')),
            ],
            options={
                'ordering': ['achievement', 'level'],
                'unique_together': {('achievement', 'level')},
            },
        ),
        migrations.CreateModel(
            name='AchievementProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='Текущее значение')),
                ('current_level', models.PositiveIntegerField(default=0, verbose_name='Достигнутый уровень')),
                ('achieved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего получения')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='DailyRewardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('claimed', models.BooleanField(default=False, verbose_name='Выдано')),
                ('streak_bonus', models.PositiveIntegerField(default=5, verbose_name='Бонус за стрик')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('test_score', models.PositiveSmallIntegerField(default=0, verbose_name='Результат теста (%)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='main.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пройденный урок',
                'verbose_name_plural': 'Пройденные уроки',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='UserLeagueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('weekly_xp', models.PositiveIntegerField(default=0, verbose_name='XP за неделю')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Место в лиге')),
                ('league_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.leagueinstance')),
                ('promotion_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from', to='main.leagueinstance')),
                ('relegation_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relegated_from', to='main.leagueinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
