# Generated by Django 5.2.12 on 2026-04-13 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('option1', models.CharField(max_length=200, verbose_name='Вариант 1')),
                ('option2', models.CharField(max_length=200, verbose_name='Вариант 2')),
                ('option3', models.CharField(blank=True, max_length=200, verbose_name='Вариант 3')),
                ('option4', models.CharField(blank=True, max_length=200, verbose_name='Вариант 4')),
                ('correct_option', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Номер правильного ответа (1-4)')),
                ('explanation', models.TextField(blank=True, verbose_name='Пояснение к ответу')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы тестов',
                'ordering': ['id'],
            },
        ),
    ]
