# Generated by Django 5.2.12 on 2026-05-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_load_full_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Для типа "audio_choice"', verbose_name='Ссылка на аудиофайл'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Выбор правильного варианта'), ('translate', 'Перевод слова/фразы'), ('audio_choice', 'Прослушать и выбрать перевод'), ('match', 'Сопоставление')], default='choice', max_length=20, verbose_name='Тип вопроса'),
        ),
    ]
