# Generated by Django 5.2.12 on 2026-04-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_create_initial_course_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.CharField(blank=True, help_text='Например: Основы, Повседневная речь', max_length=100, verbose_name='Раздел'),
        ),
    ]
