# Generated by Django 5.2.12 on 2026-04-13 20:00
from django.db import migrations
from django.utils.text import slugify

def add_missing_lessons(apps, schema_editor):
    Course = apps.get_model('main', 'Course')
    Lesson = apps.get_model('main', 'Lesson')
    Question = apps.get_model('main', 'Question')

    course = Course.objects.filter(slug='tatarskii-yazyk-s-nulya').first()
    if not course:
        return

    existing_orders = set(Lesson.objects.filter(course=course).values_list('order', flat=True))
    # Определяем, какие уроки уже есть
    # Всего должно быть 50 уроков (1-50)

    lessons_to_add = []

    # Данные для уроков 16-50 (разделы 4-10 по 5 уроков)
    # Раздел 4: Работа и учёба (уроки 16-20)
    # Раздел 5: Путешествия (21-25)
    # Раздел 6: Здоровье (26-30)
    # Раздел 7: Культура и искусство (31-35)
    # Раздел 8: Природа и животные (36-40)
    # Раздел 9: Технологии и интернет (41-45)
    # Раздел 10: Общество и новости (46-50)

    new_lessons_data = [
        # Раздел 4: Работа и учёба
        {'order':16,'section':'Работа и учёба','title':'Профессии','content':'<h3>Профессии</h3><ul><li>табиб – врач</li><li>укытучы – учитель</li><li>инженер – инженер</li><li>программист – программист</li><li>эшче – рабочий</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "врач"?','opt1':'укытучы','opt2':'табиб','opt3':'инженер','opt4':'программист','correct':2},
             {'text':'Переведите "учитель":','opt1':'укытучы','opt2':'укучы','opt3':'мәктәп','opt4':'дәрес','correct':1},
             {'text':'"Эшче" – это:','opt1':'инженер','opt2':'рабочий','opt3':'директор','opt4':'менеджер','correct':2},
             {'text':'Как спросить "Кем эшлисез?"','opt1':'Кем вы?','opt2':'Кем работаете?','opt3':'Где работаете?','opt4':'Что делаете?','correct':2},
             {'text':'Программист по-татарски:','opt1':'программист','opt2':'эшче','opt3':'мөхәррир','opt4':'дизайнер','correct':1},
         ]},
        {'order':17,'section':'Работа и учёба','title':'Офис и техника','content':'<h3>Офисные предметы</h3><ul><li>компьютер – компьютер</li><li>принтер – принтер</li><li>кагазь – бумага</li><li>каләм – ручка</li><li>өстәл – стол</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "компьютер"?','opt1':'компьютер','opt2':'ноутбук','opt3':'планшет','opt4':'телефон','correct':1},
             {'text':'Что значит "кагазь"?','opt1':'тетрадь','opt2':'бумага','opt3':'книга','opt4':'журнал','correct':2},
             {'text':'Ручка по-татарски:','opt1':'каләм','opt2':'буяу','opt3':'фломастер','opt4':'маркер','correct':1},
         ]},
        {'order':18,'section':'Работа и учёба','title':'Университет','content':'<h3>Учёба</h3><ul><li>университет – университет</li><li>студент – студент</li><li>укыту – обучение</li><li>дәрес – пара/урок</li><li>имтихан – экзамен</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "экзамен"?','opt1':'имтихан','opt2':'дәрес','opt3':'контроль','opt4':'тест','correct':1},
             {'text':'Переведите "студент":','opt1':'студент','opt2':'укытучы','opt3':'мәктәп','opt4':'дәрес','correct':1},
         ]},
        {'order':19,'section':'Работа и учёба','title':'Собеседование','content':'<h3>Вопросы на собеседовании</h3><ul><li>Эш тәҗрибәгез бармы? – Есть опыт работы?</li><li>Сез ничек уйлыйсыз? – Что вы думаете?</li></ul>','duration':20,
         'questions':[
             {'text':'Как спросить "Есть опыт работы?"','opt1':'Эш тәҗрибәгез бармы?','opt2':'Эшләдегезме?','opt3':'Кая эшләдегез?','opt4':'Ничә ел эшләдегез?','correct':1},
         ]},
        {'order':20,'section':'Работа и учёба','title':'Деловая переписка','content':'<h3>Фразы</h3><ul><li>Хөрмәтле... – Уважаемый...</li><li>Зинһар – Пожалуйста</li><li>Рәхмәт – Спасибо</li></ul>','duration':20,
         'questions':[
             {'text':'Как начать письмо "Уважаемый"?','opt1':'Хөрмәтле','opt2':'Исәнмесез','opt3':'Рәхим итегез','opt4':'Сау булыгыз','correct':1},
         ]},
        # Раздел 5: Путешествия (21-25)
        {'order':21,'section':'Путешествия','title':'Вокзал и аэропорт','content':'<h3>Транспорт</h3><ul><li>поезд – поезд</li><li>самолёт – самолёт</li><li>билет – билет</li><li>багаж – багаж</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "билет"?','opt1':'билет','opt2':'паспорт','opt3':'вагон','opt4':'вокзал','correct':1},
         ]},
        {'order':22,'section':'Путешествия','title':'Гостиница','content':'<h3>В отеле</h3><ul><li>номер – номер</li><li>бронь – бронь</li><li>ачкыч – ключ</li></ul>','duration':20,
         'questions':[
             {'text':'Ключ по-татарски:','opt1':'ачкыч','opt2':'ишек','opt3':'замок','opt4':'тоткыч','correct':1},
         ]},
        {'order':23,'section':'Путешествия','title':'Ориентация в городе','content':'<h3>Как пройти?</h3><ul><li>уңга – направо</li><li>сулга – налево</li><li>туры – прямо</li><li>якында – рядом</li></ul>','duration':20,
         'questions':[
             {'text':'Как сказать "направо"?','opt1':'уңга','opt2':'сулга','opt3':'туры','opt4':'артка','correct':1},
         ]},
        {'order':24,'section':'Путешествия','title':'В ресторане','content':'<h3>Заказ еды</h3><ul><li>Меню китерегез – Принесите меню</li><li>Бу бик тәмле – Это очень вкусно</li></ul>','duration':20,
         'questions':[
             {'text':'Как сказать "Это очень вкусно"?','opt1':'Бу бик тәмле','opt2':'Бу начар','opt3':'Бу кызык','opt4':'Бу арзан','correct':1},
         ]},
        {'order':25,'section':'Путешествия','title':'Экскурсии','content':'<h3>Экскурсия</h3><ul><li>экскурсовод – экскурсовод</li><li>тарих – история</li><li>музей – музей</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "музей"?','opt1':'музей','opt2':'китапханә','opt3':'театр','opt4':'цирк','correct':1},
         ]},
        # Раздел 6: Здоровье (26-30)
        {'order':26,'section':'Здоровье','title':'Части тела','content':'<h3>Тело</h3><ul><li>баш – голова</li><li>кул – рука</li><li>аяк – нога</li><li>күз – глаз</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "голова"?','opt1':'баш','opt2':'кул','opt3':'аяк','opt4':'күз','correct':1},
         ]},
        {'order':27,'section':'Здоровье','title':'У врача','content':'<h3>Симптомы</h3><ul><li>авырту – боль</li><li>температура – температура</li><li>таблетка – таблетка</li></ul>','duration':20,
         'questions':[
             {'text':'Как сказать "У меня болит голова"?','opt1':'Башым авырта','opt2':'Кулым авырта','opt3':'Аягым авырта','opt4':'Күзем авырта','correct':1},
         ]},
        {'order':28,'section':'Здоровье','title':'Аптека','content':'<h3>Лекарства</h3><ul><li>дару – лекарство</li><li>рецепт – рецепт</li></ul>','duration':20,
         'questions':[
             {'text':'Лекарство по-татарски:','opt1':'дару','opt2':'авыру','opt3':'шифаханә','opt4':'табиб','correct':1},
         ]},
        {'order':29,'section':'Здоровье','title':'Спорт','content':'<h3>Виды спорта</h3><ul><li>футбол – футбол</li><li>хоккей – хоккей</li><li>теннис – теннис</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "хоккей"?','opt1':'хоккей','opt2':'футбол','opt3':'волейбол','opt4':'баскетбол','correct':1},
         ]},
        {'order':30,'section':'Здоровье','title':'Здоровый образ жизни','content':'<h3>Привычки</h3><ul><li>сәламәтлек – здоровье</li><li>зарядка – зарядка</li><li>режим – режим</li></ul>','duration':20,
         'questions':[
             {'text':'Что значит "сәламәтлек"?','opt1':'здоровье','opt2':'болезнь','opt3':'лекарство','opt4':'спорт','correct':1},
         ]},
        # Раздел 7: Культура и искусство (31-35)
        {'order':31,'section':'Культура','title':'Музыка','content':'<h3>Музыкальные инструменты</h3><ul><li>курай – курай</li><li>гармун – гармонь</li><li>кыл – струна</li></ul>','duration':20,
         'questions':[
             {'text':'Татарский народный инструмент:','opt1':'курай','opt2':'баян','opt3':'скрипка','opt4':'рояль','correct':1},
         ]},
        {'order':32,'section':'Культура','title':'Литература','content':'<h3>Писатели</h3><ul><li>Габдулла Тукай</li><li>Муса Җәлил</li></ul>','duration':20,
         'questions':[
             {'text':'Кто автор "Шүрәле"?','opt1':'Габдулла Тукай','opt2':'Муса Җәлил','opt3':'Каюм Насыйри','opt4':'Сибгат Хаким','correct':1},
         ]},
        {'order':33,'section':'Культура','title':'Театр','content':'<h3>Театр</h3><ul><li>спектакль – спектакль</li><li>роль – роль</li><li>сәхнә – сцена</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "сцена"?','opt1':'сәхнә','opt2':'зал','opt3':'билет','opt4':'кулиса','correct':1},
         ]},
        {'order':34,'section':'Культура','title':'Праздники','content':'<h3>Праздники</h3><ul><li>Сабантуй</li><li>Корбан бәйрәме</li><li>Ураза бәйрәме</li></ul>','duration':20,
         'questions':[
             {'text':'Какой праздник связан с окончанием поста?','opt1':'Ураза бәйрәме','opt2':'Корбан бәйрәме','opt3':'Сабантуй','opt4':'Науруз','correct':1},
         ]},
        {'order':35,'section':'Культура','title':'Традиции','content':'<h3>Обычаи</h3><ul><li>туй – свадьба</li><li>бәби туе – рождение ребёнка</li><li>кунак – гость</li></ul>','duration':20,
         'questions':[
             {'text':'Свадьба по-татарски:','opt1':'туй','opt2':'бәйрәм','opt3':'җыен','opt4':'мәҗлес','correct':1},
         ]},
        # Раздел 8: Природа и животные (36-40)
        {'order':36,'section':'Природа','title':'Животные','content':'<h3>Животные</h3><ul><li>песи – кошка</li><li>эт – собака</li><li>сыер – корова</li><li>ат – лошадь</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "собака"?','opt1':'эт','opt2':'песи','opt3':'сыер','opt4':'ат','correct':1},
         ]},
        {'order':37,'section':'Природа','title':'Птицы','content':'<h3>Птицы</h3><ul><li>кош – птица</li><li>күгәрчен – голубь</li><li>карга – ворона</li></ul>','duration':20,
         'questions':[
             {'text':'Ворона по-татарски:','opt1':'карга','opt2':'күгәрчен','opt3':'саескан','opt4':'торна','correct':1},
         ]},
        {'order':38,'section':'Природа','title':'Растения','content':'<h3>Растения</h3><ul><li>ағач – дерево</li><li>үлән – трава</li><li>чәчәк – цветок</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "цветок"?','opt1':'чәчәк','opt2':'үлән','opt3':'ағач','opt4':'бөртеге','correct':1},
         ]},
        {'order':39,'section':'Природа','title':'Погода','content':'<h3>Явления</h3><ul><li>яңгыр – дождь</li><li>кар – снег</li><li>җил – ветер</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "ветер"?','opt1':'җил','opt2':'яңгыр','opt3':'кар','opt4':'болыт','correct':1},
         ]},
        {'order':40,'section':'Природа','title':'Времена года','content':'<h3>Сезоны</h3><ul><li>яз – весна</li><li>җәй – лето</li><li>көз – осень</li><li>кыш – зима</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "зима"?','opt1':'кыш','opt2':'яз','opt3':'җәй','opt4':'көз','correct':1},
         ]},
        # Раздел 9: Технологии и интернет (41-45)
        {'order':41,'section':'Технологии','title':'Компьютер','content':'<h3>Части ПК</h3><ul><li>экран – экран</li><li>төймә – кнопка</li><li>тычкан – мышь</li></ul>','duration':20,
         'questions':[
             {'text':'Мышь компьютерная:','opt1':'тычкан','opt2':'экран','opt3':'төймә','opt4':'планшет','correct':1},
         ]},
        {'order':42,'section':'Технологии','title':'Интернет','content':'<h3>Слова</h3><ul><li>сайт – сайт</li><li>электрон почта – email</li><li>пароль – пароль</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "пароль"?','opt1':'пароль','opt2':'логин','opt3':'шифр','opt4':'код','correct':1},
         ]},
        {'order':43,'section':'Технологии','title':'Соцсети','content':'<h3>Соцсети</h3><ul><li>пост – пост</li><li>лайк – лайк</li><li>комментарий – комментарий</li></ul>','duration':20,
         'questions':[
             {'text':'Лайк по-татарски:','opt1':'лайк','opt2':'ярату','opt3':'басу','opt4':'җыю','correct':1},
         ]},
        {'order':44,'section':'Технологии','title':'Мобильные приложения','content':'<h3>Приложения</h3><ul><li>кушымта – приложение</li><li>йөкләү – скачать</li><li>керү – войти</li></ul>','duration':20,
         'questions':[
             {'text':'Как сказать "скачать"?','opt1':'йөкләү','opt2':'керү','opt3':'чыгу','opt4':'ачу','correct':1},
         ]},
        {'order':45,'section':'Технологии','title':'Безопасность','content':'<h3>Безопасность</h3><ul><li>вирус – вирус</li><li>защита – защита</li><li>киберһөҗүм – кибератака</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "вирус"?','opt1':'вирус','opt2':'авыру','opt3':'көндәш','opt4':'хакер','correct':1},
         ]},
        # Раздел 10: Общество и новости (46-50)
        {'order':46,'section':'Общество','title':'Новости','content':'<h3>СМИ</h3><ul><li>яңалыклар – новости</li><li>газета – газета</li><li>журналист – журналист</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "новости"?','opt1':'яңалыклар','opt2':'китап','opt3':'журнал','opt4':'телевидение','correct':1},
         ]},
        {'order':47,'section':'Общество','title':'Политика','content':'<h3>Политика</h3><ul><li>дәүләт – государство</li><li>президент – президент</li><li>закон – закон</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "государство"?','opt1':'дәүләт','opt2':'шәһәр','opt3':'район','opt4':'мәхәллә','correct':1},
         ]},
        {'order':48,'section':'Общество','title':'Экология','content':'<h3>Экология</h3><ul><li>табигать – природа</li><li>чыгарылмалар – выбросы</li><li>эко – эко</li></ul>','duration':20,
         'questions':[
             {'text':'Природа по-татарски:','opt1':'табигать','opt2':'яшел','opt3':'урман','opt4':'су','correct':1},
         ]},
        {'order':49,'section':'Общество','title':'Права человека','content':'<h3>Права</h3><ul><li>хокук – право</li><li>иркенлек – свобода</li><li>тигезлек – равенство</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "свобода"?','opt1':'иркенлек','opt2':'хокук','opt3':'тигезлек','opt4':'демократия','correct':1},
         ]},
        {'order':50,'section':'Общество','title':'Будущее','content':'<h3>Будущее</h3><ul><li>киләчәк – будущее</li><li>инновация – инновация</li><li>үсеш – развитие</li></ul>','duration':20,
         'questions':[
             {'text':'Как будет "развитие"?','opt1':'үсеш','opt2':'киләчәк','opt3':'яңалык','opt4':'эволюция','correct':1},
         ]},
    ]

    for les_data in new_lessons_data:
        if les_data['order'] not in existing_orders:
            lesson = Lesson.objects.create(
                course=course,
                order=les_data['order'],
                title=les_data['title'],
                section=les_data['section'],
                content=les_data['content'],
                duration_minutes=les_data['duration'],
                is_free_preview=True,
            )
            # Добавляем вопросы
            for q_data in les_data.get('questions', []):
                Question.objects.create(
                    lesson=lesson,
                    text=q_data['text'],
                    option1=q_data['opt1'],
                    option2=q_data['opt2'],
                    option3=q_data.get('opt3', ''),
                    option4=q_data.get('opt4', ''),
                    correct_option=q_data['correct'],
                    explanation=q_data.get('expl', ''),
                )
    # Обновляем количество уроков в курсе
    course.lessons_count = 50
    course.save()


def reverse_migration(apps, schema_editor):
    # Можно удалить добавленные уроки, но для простоты оставим пустым
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_add_coins_and_lessoncompletion'),
    ]

    operations = [
        migrations.RunPython(add_missing_lessons, reverse_migration),
    ]